# Project info
site_name: android-commons
site_description: "Common code for building rich applications around Android's theming abilities"
site_author: Projekt Development LLC.

# Repository info
repo_name: android-commons
repo_url: https://github.com/prjkt-io/android-commons
remote_branch: gh-pages
edit_uri: ''

# Copyright
copyright: 'Copyright &copy; 2019 Projekt Development LLC.'

# Theme configuration
theme:
  name: 'material'
  language: 'en'
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.svg
  palette:
    primary: 'white'
    accent: 'blue'

# Extensions
markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Side navigation
nav:
  - 'buildtools': 'buildtools'
  - 'shell': 'shell'
  - 'theme': 'theme'